gsap.to(
    ".box1",
    {
        x:800,
        duration:2,
        delay:1,
        repeat:-1,
        yoyo:true,
        backgroundColor:"pink"
    }
)
gsap.to(
    ".box2",
    {
        x:800,
        duration:3,
        delay:2,
        repeat:-1,
        yoyo:true,
        backgroundColor:"green"
    }
)
gsap.to(
    ".box3",
    {
        x:800,
        duration:3.5,
        delay:3,
        repeat:-1,
        yoyo:true,
        backgroundColor:"yellow"
    }
)
gsap.to(
    ".box4",
    {
        x:800,
        duration:4,
        delay:1,
        repeat:-1,
        yoyo:true,
        backgroundColor:"red"
    }
)
